
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
<<<<<<< HEAD
name: 'my_new_project'
=======
name: 'taxi_rides_ny'
>>>>>>> c54e95e520d995aac0ff8c68aad1fc52731619a7
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
<<<<<<< HEAD
profile: 'default'
=======
profile: 'pg-dbt-workshop'
>>>>>>> c54e95e520d995aac0ff8c68aad1fc52731619a7

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
<<<<<<< HEAD
analysis-paths: ["analyses"]
=======
analysis-paths: ["analysis"]
>>>>>>> c54e95e520d995aac0ff8c68aad1fc52731619a7
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
<<<<<<< HEAD
  - "target"
  - "dbt_packages"
=======
    - "target"
    - "dbt_packages"
    - "dbt_modules"
>>>>>>> c54e95e520d995aac0ff8c68aad1fc52731619a7


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
<<<<<<< HEAD
  my_new_project:
    # Applies to all files under models/example/
    example:
      materialized: view
=======
  taxi_rides_ny:
      # Applies to all files under models/.../
      staging:
          materialized: view
      core:
          materialized: table
vars:
  payment_type_values: [1, 2, 3, 4, 5, 6]

seeds: 
    taxi_rides_ny:
        taxi_zone_lookup:
            +column_types:
                locationid: numeric
>>>>>>> c54e95e520d995aac0ff8c68aad1fc52731619a7
